"""Khoi tao toan bo schema (Phan 5, 13.5, 14.4, 15.8)

Revision ID: 0001
Revises: 
Create Date: 2026-08-01 12:13:29.551497
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=40), nullable=True),
    sa.Column('old_value', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_target_type'), ['target_type'], unique=False)
        batch_op.create_index('ix_audit_target', ['target_type', 'target_id'], unique=False)

    op.create_table('categories',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_type'), ['type'], unique=False)
        batch_op.create_index('uq_category_code_type', ['code', 'type'], unique=True)

    op.create_table('legal_documents',
    sa.Column('type', sa.String(length=25), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('requires_reconsent', sa.Boolean(), nullable=False),
    sa.Column('summary_of_changes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'version', name='uq_legal_type_version')
    )
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_documents_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_documents_type'), ['type'], unique=False)

    op.create_table('login_logs',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('email_attempted', sa.String(length=190), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_email_attempted'), ['email_attempted'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notification_templates',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=15), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'channel', name='uq_template_code_channel')
    )
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_templates_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_templates_created_at'), ['created_at'], unique=False)

    op.create_table('packages',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_telegram_alerts', sa.Integer(), nullable=False),
    sa.Column('max_ai_questions_per_day', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_tier'), ['tier'], unique=False)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)

    op.create_table('roles',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_created_at'), ['created_at'], unique=False)

    op.create_table('staff',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_status'), ['status'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_matched', sa.Integer(), nullable=False),
    sa.Column('rows_unmatched', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_run_date'), ['run_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_syncjob_type_date', ['job_type', 'run_date'], unique=False)

    op.create_table('trading_calendar',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('trade_date')
    )
    op.create_table('trial_abuse_logs',
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('signup_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip', 'signup_date', name='uq_trial_abuse_ip_date')
    )
    with op.batch_alter_table('trial_abuse_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_abuse_logs_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=190), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('securities_account_no', sa.String(length=50), nullable=True),
    sa.Column('ib_link_status', sa.String(length=20), nullable=False),
    sa.Column('ib_link_deadline', sa.DateTime(), nullable=True),
    sa.Column('ib_linked_at', sa.DateTime(), nullable=True),
    sa.Column('broker_name', sa.String(length=150), nullable=True),
    sa.Column('broker_code', sa.String(length=50), nullable=True),
    sa.Column('broker_phone', sa.String(length=20), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('compliance_status', sa.String(length=20), nullable=False),
    sa.Column('current_subscription_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('trial_used', sa.Boolean(), nullable=False),
    sa.Column('compliance_exempt', sa.Boolean(), nullable=False),
    sa.Column('compliance_exempt_reason', sa.String(length=255), nullable=True),
    sa.Column('warning_until', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_reason', sa.String(length=255), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('latest_nav', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('latest_nav_date', sa.Date(), nullable=True),
    sa.Column('last_trade_date', sa.Date(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('signup_ip', sa.String(length=45), nullable=True),
    sa.Column('customer_code', sa.String(length=20), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_compliance_status'), ['compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_customer_type'), ['customer_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_securities_account_no'), ['securities_account_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_subscription_status'), ['subscription_status'], unique=False)
        batch_op.create_index('ix_users_two_axis', ['subscription_status', 'compliance_status'], unique=False)
        batch_op.create_index('ix_users_warning_until', ['warning_until'], unique=False)

    op.create_table('articles',
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('min_package_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('author_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['min_package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_article_status_published', ['status', 'published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    op.create_table('compliance_events',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('nav_avg_20', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('days_since_last_trade', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=10), nullable=False),
    sa.Column('staff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_events_user_id'), ['user_id'], unique=False)

    op.create_table('customer_notes',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('staff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_notes_user_id'), ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('min_package_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('uploaded_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['min_package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_is_active'), ['is_active'], unique=False)

    op.create_table('email_verifications',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verifications_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verifications_user_id'), ['user_id'], unique=False)

    op.create_table('nav_daily',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('last_trade_date', sa.Date(), nullable=True),
    sa.Column('order_count_30d', sa.Integer(), nullable=True),
    sa.Column('account_no', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('sync_job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_date', name='uq_nav_user_date')
    )
    with op.batch_alter_table('nav_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nav_daily_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_daily_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_nav_daily_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_nav_user_date_desc', ['user_id', 'trade_date'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=15), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', 'channel', name='uq_pref')
    )
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preferences_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=15), nullable=False),
    sa.Column('reference_id', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', 'reference_id', 'channel', name='uq_notification_once')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_queue', ['status', 'scheduled_at'], unique=False)
        batch_op.create_index('ix_notif_user_unread', ['user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('permission_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('staff_roles',
    sa.Column('staff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'role_id')
    )
    op.create_table('staff_sessions',
    sa.Column('staff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('staff_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_sessions_staff_id'), ['staff_id'], unique=False)

    op.create_table('strategies',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('school', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules_summary', sa.Text(), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('owner_type', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('min_package_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('analyst_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['min_package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_school'), ['school'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_status'), ['status'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('package_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('frozen_days', sa.Integer(), nullable=False),
    sa.Column('frozen_since', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_type', sa.String(length=10), nullable=False),
    sa.Column('created_by_staff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_sub_user_current', ['user_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('sync_unmatched',
    sa.Column('sync_job_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('email_in_sheet', sa.String(length=190), nullable=True),
    sa.Column('account_no', sa.String(length=50), nullable=True),
    sa.Column('nav', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_unmatched', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_unmatched_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_unmatched_email_in_sheet'), ['email_in_sheet'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_unmatched_sync_job_id'), ['sync_job_id'], unique=False)

    op.create_table('telegram_connections',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('telegram_first_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('connect_token', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('verify_code_hash', sa.String(length=64), nullable=True),
    sa.Column('verify_code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('verify_attempts', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('telegram_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_connections_chat_id'), ['chat_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_telegram_connections_connect_token'), ['connect_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_connections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_connections_status'), ['status'], unique=False)

    op.create_table('telegram_daily_counters',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('send_date', sa.Date(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('deferred', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'send_date', name='uq_tg_counter')
    )
    op.create_table('user_consents',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('legal_document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['legal_document_id'], ['legal_documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'legal_document_id', name='uq_consent_once')
    )
    with op.batch_alter_table('user_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_consents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_consents_legal_document_id'), ['legal_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_consents_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('article_versions',
    sa.Column('article_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('change_note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_versions_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_versions_created_at'), ['created_at'], unique=False)

    op.create_table('article_views',
    sa.Column('article_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_views_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_views_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_views_user_id'), ['user_id'], unique=False)

    op.create_table('document_downloads',
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('watermarked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_downloads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_downloads_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_downloads_user_id'), ['user_id'], unique=False)

    op.create_table('signals',
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tp', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_reason', sa.String(length=10), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('r_multiple', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signal_strategy_symbol_time', ['strategy_id', 'symbol', 'entry_time'], unique=False)
        batch_op.create_index('ix_signal_type_result', ['signal_type', 'result'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_entry_time'), ['entry_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)

    op.create_table('strategy_alerts',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('alert_types', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('inactive_reason', sa.String(length=30), nullable=True),
    sa.Column('inactive_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_id', 'symbol', name='uq_alert_pair')
    )
    with op.batch_alter_table('strategy_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_hot', ['strategy_id', 'symbol', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_faq',
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_question_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_faq_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_faq_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('strategy_kb_docs',
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('index_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'document_id', name='uq_kb_doc')
    )
    with op.batch_alter_table('strategy_kb_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_kb_docs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_kb_docs_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('strategy_stats',
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_r', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('max_dd', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'symbol', 'signal_type', name='uq_stat_scope')
    )
    with op.batch_alter_table('strategy_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_stats_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_stats_symbol'), ['symbol'], unique=False)

    op.create_table('strategy_symbols',
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'symbol', name='uq_strategy_symbol')
    )
    with op.batch_alter_table('strategy_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_symbols_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_symbols_symbol'), ['symbol'], unique=False)

    op.create_table('alert_deliveries',
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('alert_type', sa.String(length=15), nullable=False),
    sa.Column('channel', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('skip_reason', sa.String(length=40), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'user_id', 'alert_type', name='uq_delivery_once')
    )
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_deliveries_next_retry_at'), ['next_retry_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_deliveries_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_deliveries_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_questions',
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('answer_type', sa.String(length=10), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_questions_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_questions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_questions_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_questions_sla_due_at'), ['sla_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_questions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_questions_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_questions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_questions_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_questions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_questions_status'))
        batch_op.drop_index(batch_op.f('ix_strategy_questions_sla_due_at'))
        batch_op.drop_index(batch_op.f('ix_strategy_questions_is_public'))
        batch_op.drop_index(batch_op.f('ix_strategy_questions_created_at'))
        batch_op.drop_index(batch_op.f('ix_strategy_questions_assigned_to'))

    op.drop_table('strategy_questions')
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_signal_id'))
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_next_retry_at'))

    op.drop_table('alert_deliveries')
    with op.batch_alter_table('strategy_symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_symbols_symbol'))
        batch_op.drop_index(batch_op.f('ix_strategy_symbols_strategy_id'))

    op.drop_table('strategy_symbols')
    with op.batch_alter_table('strategy_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_stats_symbol'))
        batch_op.drop_index(batch_op.f('ix_strategy_stats_strategy_id'))

    op.drop_table('strategy_stats')
    with op.batch_alter_table('strategy_kb_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_kb_docs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_kb_docs_created_at'))

    op.drop_table('strategy_kb_docs')
    with op.batch_alter_table('strategy_faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_faq_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_faq_created_at'))

    op.drop_table('strategy_faq')
    with op.batch_alter_table('strategy_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_alerts_created_at'))
        batch_op.drop_index('ix_alert_hot')

    op.drop_table('strategy_alerts')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_signals_result'))
        batch_op.drop_index(batch_op.f('ix_signals_entry_time'))
        batch_op.drop_index(batch_op.f('ix_signals_created_at'))
        batch_op.drop_index('ix_signal_type_result')
        batch_op.drop_index('ix_signal_strategy_symbol_time')

    op.drop_table('signals')
    with op.batch_alter_table('document_downloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_downloads_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_downloads_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_downloads_created_at'))

    op.drop_table('document_downloads')
    with op.batch_alter_table('article_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_article_views_created_at'))
        batch_op.drop_index(batch_op.f('ix_article_views_article_id'))

    op.drop_table('article_views')
    with op.batch_alter_table('article_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_article_versions_article_id'))

    op.drop_table('article_versions')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_created_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_consents_legal_document_id'))
        batch_op.drop_index(batch_op.f('ix_user_consents_created_at'))

    op.drop_table('user_consents')
    op.drop_table('telegram_daily_counters')
    with op.batch_alter_table('telegram_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_connections_status'))
        batch_op.drop_index(batch_op.f('ix_telegram_connections_created_at'))
        batch_op.drop_index(batch_op.f('ix_telegram_connections_connect_token'))
        batch_op.drop_index(batch_op.f('ix_telegram_connections_chat_id'))

    op.drop_table('telegram_connections')
    with op.batch_alter_table('sync_unmatched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_unmatched_sync_job_id'))
        batch_op.drop_index(batch_op.f('ix_sync_unmatched_email_in_sheet'))
        batch_op.drop_index(batch_op.f('ix_sync_unmatched_created_at'))

    op.drop_table('sync_unmatched')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_payment_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_is_current'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))
        batch_op.drop_index('ix_sub_user_current')

    op.drop_table('subscriptions')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_status'))
        batch_op.drop_index(batch_op.f('ix_strategies_school'))
        batch_op.drop_index(batch_op.f('ix_strategies_owner_id'))
        batch_op.drop_index(batch_op.f('ix_strategies_created_at'))

    op.drop_table('strategies')
    with op.batch_alter_table('staff_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_sessions_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_sessions_refresh_token_hash'))
        batch_op.drop_index(batch_op.f('ix_staff_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_staff_sessions_created_at'))

    op.drop_table('staff_sessions')
    op.drop_table('staff_roles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_created_at'))

    op.drop_table('password_resets')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_code'))
        batch_op.drop_index(batch_op.f('ix_notifications_channel'))
        batch_op.drop_index('ix_notif_user_unread')
        batch_op.drop_index('ix_notif_queue')

    op.drop_table('notifications')
    with op.batch_alter_table('notification_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_preferences_created_at'))

    op.drop_table('notification_preferences')
    with op.batch_alter_table('nav_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_nav_user_date_desc')
        batch_op.drop_index(batch_op.f('ix_nav_daily_user_id'))
        batch_op.drop_index(batch_op.f('ix_nav_daily_trade_date'))
        batch_op.drop_index(batch_op.f('ix_nav_daily_created_at'))

    op.drop_table('nav_daily')
    with op.batch_alter_table('email_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_verifications_created_at'))

    op.drop_table('email_verifications')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_is_active'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_category_id'))

    op.drop_table('documents')
    with op.batch_alter_table('customer_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_notes_created_at'))

    op.drop_table('customer_notes')
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_events_event'))
        batch_op.drop_index(batch_op.f('ix_compliance_events_created_at'))

    op.drop_table('compliance_events')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_published_at'))
        batch_op.drop_index(batch_op.f('ix_articles_created_at'))
        batch_op.drop_index(batch_op.f('ix_articles_category_id'))
        batch_op.drop_index(batch_op.f('ix_articles_author_id'))
        batch_op.drop_index('ix_article_status_published')

    op.drop_table('articles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_warning_until')
        batch_op.drop_index('ix_users_two_axis')
        batch_op.drop_index(batch_op.f('ix_users_subscription_status'))
        batch_op.drop_index(batch_op.f('ix_users_securities_account_no'))
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_users_customer_type'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index(batch_op.f('ix_users_compliance_status'))

    op.drop_table('users')
    with op.batch_alter_table('trial_abuse_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_abuse_logs_created_at'))

    op.drop_table('trial_abuse_logs')
    op.drop_table('trading_calendar')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_syncjob_type_date')
        batch_op.drop_index(batch_op.f('ix_sync_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_run_date'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_job_type'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_status'))
        batch_op.drop_index(batch_op.f('ix_staff_created_at'))

    op.drop_table('staff')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_created_at'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_module'))

    op.drop_table('permissions')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_tier'))
        batch_op.drop_index(batch_op.f('ix_packages_created_at'))

    op.drop_table('packages')
    with op.batch_alter_table('notification_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_templates_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_templates_code'))

    op.drop_table('notification_templates')
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_logs_result'))
        batch_op.drop_index(batch_op.f('ix_login_logs_ip'))
        batch_op.drop_index(batch_op.f('ix_login_logs_email_attempted'))
        batch_op.drop_index(batch_op.f('ix_login_logs_created_at'))

    op.drop_table('login_logs')
    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_documents_type'))
        batch_op.drop_index(batch_op.f('ix_legal_documents_is_current'))
        batch_op.drop_index(batch_op.f('ix_legal_documents_created_at'))

    op.drop_table('legal_documents')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('uq_category_code_type')
        batch_op.drop_index(batch_op.f('ix_categories_type'))
        batch_op.drop_index(batch_op.f('ix_categories_created_at'))

    op.drop_table('categories')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_target')
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
