"""Du lieu thi truong: symbols, ohlcv_daily, corporate_actions (Phan 12)

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-01 17:12:21.133146
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cash_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'ex_date', 'action_type', name='uq_corp_action')
    )
    op.create_index(op.f('ix_corporate_actions_created_at'), 'corporate_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_symbol'), 'corporate_actions', ['symbol'], unique=False)
    op.create_table('market_sync_logs',
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('symbols_total', sa.Integer(), nullable=False),
    sa.Column('symbols_synced', sa.Integer(), nullable=False),
    sa.Column('symbols_failed', sa.Integer(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('anomalies', sa.JSON().with_variant(mysql.JSON(), 'mysql'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_sync_logs_created_at'), 'market_sync_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_sync_logs_run_date'), 'market_sync_logs', ['run_date'], unique=False)
    op.create_table('ohlcv_daily',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trade_date', name='uq_ohlcv_symbol_date')
    )
    op.create_index('ix_ohlcv_symbol_date', 'ohlcv_daily', ['symbol', 'trade_date'], unique=False)
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_name_en', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_ohlcv_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_symbol_exchange_active', 'symbols', ['exchange', 'is_active'], unique=False)
    op.create_index(op.f('ix_symbols_created_at'), 'symbols', ['created_at'], unique=False)
    op.create_index(op.f('ix_symbols_exchange'), 'symbols', ['exchange'], unique=False)
    op.create_index(op.f('ix_symbols_industry'), 'symbols', ['industry'], unique=False)
    op.create_index(op.f('ix_symbols_is_active'), 'symbols', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbols_is_active'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_industry'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_exchange'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_created_at'), table_name='symbols')
    op.drop_index('ix_symbol_exchange_active', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_ohlcv_symbol_date', table_name='ohlcv_daily')
    op.drop_table('ohlcv_daily')
    op.drop_index(op.f('ix_market_sync_logs_run_date'), table_name='market_sync_logs')
    op.drop_index(op.f('ix_market_sync_logs_created_at'), table_name='market_sync_logs')
    op.drop_table('market_sync_logs')
    op.drop_index(op.f('ix_corporate_actions_symbol'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_created_at'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
