"""strategy_shares: chia se chien luoc ca nhan

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-01 17:41:28.775642
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_shares',
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('shared_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('shared_with_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'shared_with_user_id', name='uq_share_target')
    )
    op.create_index('ix_share_active', 'strategy_shares', ['shared_with_user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_strategy_shares_created_at'), 'strategy_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_shares_share_token'), 'strategy_shares', ['share_token'], unique=True)
    op.create_index(op.f('ix_strategy_shares_shared_by_user_id'), 'strategy_shares', ['shared_by_user_id'], unique=False)
    op.create_index(op.f('ix_strategy_shares_shared_with_user_id'), 'strategy_shares', ['shared_with_user_id'], unique=False)
    op.create_index(op.f('ix_strategy_shares_strategy_id'), 'strategy_shares', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_shares_strategy_id'), table_name='strategy_shares')
    op.drop_index(op.f('ix_strategy_shares_shared_with_user_id'), table_name='strategy_shares')
    op.drop_index(op.f('ix_strategy_shares_shared_by_user_id'), table_name='strategy_shares')
    op.drop_index(op.f('ix_strategy_shares_share_token'), table_name='strategy_shares')
    op.drop_index(op.f('ix_strategy_shares_created_at'), table_name='strategy_shares')
    op.drop_index('ix_share_active', table_name='strategy_shares')
    op.drop_table('strategy_shares')
    # ### end Alembic commands ###
