"""staff_notifications

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-01 18:06:24.656345
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_notifications',
    sa.Column('staff_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('required_permission', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_notif_unread', 'staff_notifications', ['staff_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_staff_notifications_code'), 'staff_notifications', ['code'], unique=False)
    op.create_index(op.f('ix_staff_notifications_created_at'), 'staff_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_staff_notifications_read_at'), 'staff_notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_staff_notifications_staff_id'), 'staff_notifications', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_notifications_staff_id'), table_name='staff_notifications')
    op.drop_index(op.f('ix_staff_notifications_read_at'), table_name='staff_notifications')
    op.drop_index(op.f('ix_staff_notifications_created_at'), table_name='staff_notifications')
    op.drop_index(op.f('ix_staff_notifications_code'), table_name='staff_notifications')
    op.drop_index('ix_staff_notif_unread', table_name='staff_notifications')
    op.drop_table('staff_notifications')
    # ### end Alembic commands ###
